### ISSUE TITLE
What is 1/n in summation when you pulled x[i] into summation?

### ISSUE THREAD

**Issue by aazimkhan19** [peterhurford/intro-stats-learn-notes#3]
In Linear Regression problemset, exersize 5. 

y^[i]

= x[i] * (Σ{i = 1 -> n}(x[i]y[i])) / (Σ{j = 1 -> n}(x[j]^2))

= x[i] * (Σ{i = 1 -> n}((x[i]y[i])/x[i]^2))

= x[i] * (Σ{i = 1 -> n}( (1/x[i]^2) * x[i] * y[i] )

= Σ{i = 1 -> n}( (1/n) * x[i] * (1/x[i]^2) * x[i] * y[i] )

= Σ{j = 1 -> n}(a[j]y[j]) where a[j] = (1/n) * x[j] * (1/x[j]^2) * x[j]

= Σ{j = 1 -> n}(a[j]y[j]) where a[j] = x[j] * (1/n**x[j]^2) * x[j]

= Σ{j = 1 -> n}(a[j]y[j]) where a[j] = (1/n**x[j]^2) * x[j]^2

= Σ{j = 1 -> n}(a[j]y[j]) where a[j] = (x[j]^2) / (n**x[j]^2)

= Σ{j = 1 -> n}(a[j]y[j]) where a[j] = 1/n

we get 1/n in summation when you take x[i] into summation. Also here **x[j] * (1/n\*\*x[j]^2) * x[j]** sign ** means power?

**Comment by peterhurford** [comment]
Where are you seeing that?
